name: Deploy Lambda

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up function
        uses: actions/set-up-python@v2
        with:
          python-version: 3.8
      - run: |
          pwd
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          